os: linux
dist: focal
language: go
jobs:
 include: 
 - name: “test” # existing functionality
   script: # existing functionality
    - go version
 - name: “sbom”
   script: # existing functionality
     - cd go
     - go version
   addons:
     sbom:
       on:
         branch: 'main'
         pr: false
       # condition: false
       run_phase: "after_failure" # 
       output_format: "cyclonedx-xml" # 
       output_dir: "/test" # 
       input_dir: "/go" #
