os: linux
dist: focal
language: go
jobs:
 include: 
 - name: “test” # existing functionality
   script: # existing functionality
    - go version
 - name: “sbom”
   script: # existing functionality
     - cd go
     - go version
   addons:
     sbom:
       on:
         branch: 'main'
         pr: true
       # condition: true
       run_phase: "before_script" # 
       output_format: "spdx-json" # 
       output_dir: "/test" # 
       input_dir: "/go" #
